import React,{useState} from 'react';
import {Text,Alert} from 'react-native';
import {Page,Field,Choice,Button} from '../components/UI';
import {useFinance} from '../storage/FinanceContext';
import {Kind} from '../types';
import {parseMoney,today,uid,validate} from '../services/finance';
import {s} from '../styles/theme';
export default function Form({navigation,route}:any){const {db,commit,busy}=useFinance();const old=db.lancamentos.find(t=>t.id===route.params?.id);const [descricao,setDesc]=useState(old?.descricao||''),[valor,setValor]=useState(old?(old.valor/100).toFixed(2).replace('.',','):''),[data,setData]=useState(old?.data||today()),[tipo,setTipo]=useState<Kind>(old?.tipo||'despesa'),[contaId,setConta]=useState(old?.contaId||db.contas[0]?.id||''),[categoriaId,setCategoria]=useState(old?.categoriaId||''),[error,setError]=useState('');
 async function submit(){const tx={descricao:descricao.trim(),valor:parseMoney(valor)??0,data,tipo,contaId,categoriaId};const e=validate(tx,db);if(e){setError(e);return;}try{await commit(d=>({...d,lancamentos:old?d.lancamentos.map(t=>t.id===old.id?{...tx,id:old.id}:t):[...d.lancamentos,{...tx,id:uid()}]}));Alert.alert('Sucesso','Lançamento salvo.');navigation.goBack();}catch{setError('Não foi possível salvar. Tente novamente.');}}
 return <Page title={old?'Editar lançamento':'Novo lançamento'}><Choice value={tipo} onChange={v=>{setTipo(v as Kind);setCategoria('');}} items={[{id:'receita',nome:'Receita'},{id:'despesa',nome:'Despesa'}]}/><Field label="Descrição" value={descricao} onChangeText={setDesc} maxLength={100}/><Field label="Valor em reais (ex.: 25,90)" value={valor} onChangeText={setValor} keyboardType="decimal-pad"/><Field label="Data (AAAA-MM-DD)" value={data} onChangeText={setData} maxLength={10}/><Text style={s.label}>Conta</Text><Choice items={db.contas} value={contaId} onChange={setConta}/><Text style={s.label}>Categoria</Text><Choice items={db.categorias.filter(c=>c.tipo===tipo)} value={categoriaId} onChange={setCategoria}/>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}<Button title={busy?'Salvando...':'Salvar lançamento'} onPress={()=>void submit()} disabled={busy}/><Button title="Cancelar" onPress={()=>navigation.goBack()}/></Page>;}
